language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t react-image -f Dockerfile.dev .

script:
        - docker run -e CI=true  react-image npm run test 

deploy:
        edge: true
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-2-382506126312"
        bucket_path: "docker-react"
        on:     
                branch: master
        acces_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
             
                

